server:
  port: 8090
  session-timeout: 30
  tomcat.max-threads: 1
  tomcat.uri-encoding: utf8


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/playground?characterEncoding=utf8
    username: rundong
    password: rundong
    driverClassName: com.mysql.cj.jdbc.Driver
#  jpa:
#      database: MYSQL
#      show-sql: true
#    hibernate:
#      ddl-auto: update
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#    properties:
#      hibernate:
